FROM pravsingh/hygieia-jenkins-build-collector

ENV MONGO_PORT tcp://devops-hygieiadb:27017

ENV HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE hygieia

ENV MONGODB_HOST devops-hygieiadb

ENV MONGODB_PORT 27017

ENV HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME admin

ENV HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD zaq12wsx

ENV JENKINS_CRON 0 0/5 * * * *

ENV JENKINS_MASTER http://devops-jenkins:8080

ENV JENKINS_USERNAME devopsadmin

ENV JENKINS_API_KEY d5a282d50daa2e282a03fb3110d8645a

ENV JENKINS_NAME devops-jenkins





